test:
  sections:
    page_header:
      components:
        -
          name: header
          depth: 2
          content: "Hello World"
    content:
      components:
        -
          name: introp
          content: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    sidebar:
      components:
        -
          name: tout
          title: "A Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
        -
          name: cta
          title: Be More Awesome!
          blurb: "It's clearly the better choice."
          link: "/awesome"
          background: /images/ctabackground.jpg
anothertest:
  sections:
    lede:
      components:
        -
          name: lede
          depth: 2
          content: "Hello World"
    touts:
      components:
        -
          name: tout
          title: "1) Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
        -
          name: tout
          title: "2) Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
        -
          name: tout
          title: "3) Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
        -
          name: tout
          title: "4) Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
        -
          name: tout
          title: "5) Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
        -
          name: tout
          title: "6) Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
        -
          name: tout
          title: "7) Tout"
          blurb: Hi didly yall
          image: /images/placeholder.jpg
